In [2]:
import torch
import pandas as pd

In [9]:
points = torch.full([3, 3], 6)
points

tensor([[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]])

In [10]:
torch.save(points, 'D:/Code/PythonCode/pytorch-deep-learning-action/data/3/ourpoints.t')

In [12]:
new_p = torch.load('D:/Code/PythonCode/pytorch-deep-learning-action/data/3/ourpoints.t', weights_only=True)
new_p

tensor([[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]])

In [13]:
with open('D:/Code/PythonCode/pytorch-deep-learning-action/data/3/ourpoints.t', 'rb') as f:
    new_points = torch.load(f, weights_only=True)
new_points

tensor([[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]])

In [14]:
import h5py

In [15]:
points = torch.ones(3, 3)
f = h5py.File('D:/Code/PythonCode/pytorch-deep-learning-action/data/3/ourpoints.hdf5', 'w')
dset = f.create_dataset('points', data=points.numpy())
f.close()

In [16]:
f = h5py.File('D:/Code/PythonCode/pytorch-deep-learning-action/data/3/ourpoints.hdf5', 'r')
dset = f['points']
last_points = torch.from_numpy(dset[:])
f.close()
last_points

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [17]:
a = torch.ones((4, 5))
a

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [18]:
cat_a1 = torch.cat([a, a], dim=0)
cat_a1

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [19]:
cat_a2 = torch.cat([a, a], dim=1)
cat_a2

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [20]:
a = torch.normal(0, 1, (3, 4))
b = torch.normal(0, 1, (3, 4))
a

tensor([[-1.6491, -0.2472,  0.4581,  0.1088],
        [ 0.3564, -0.1417,  0.9881,  1.3076],
        [-0.0697, -0.2187,  1.3871,  1.2054]])

In [21]:
cat_ab1 = torch.stack([a, b], dim=0)
cat_ab1

tensor([[[-1.6491, -0.2472,  0.4581,  0.1088],
         [ 0.3564, -0.1417,  0.9881,  1.3076],
         [-0.0697, -0.2187,  1.3871,  1.2054]],

        [[-0.6229,  0.0794,  0.7143,  0.2698],
         [-0.2063, -0.2342, -0.5200,  0.9406],
         [-1.1595,  0.7688,  0.1383,  0.9282]]])

In [22]:
cat_ab2 = torch.stack([a, b], dim=2)
cat_ab2

tensor([[[-1.6491, -0.6229],
         [-0.2472,  0.0794],
         [ 0.4581,  0.7143],
         [ 0.1088,  0.2698]],

        [[ 0.3564, -0.2063],
         [-0.1417, -0.2342],
         [ 0.9881, -0.5200],
         [ 1.3076,  0.9406]],

        [[-0.0697, -1.1595],
         [-0.2187,  0.7688],
         [ 1.3871,  0.1383],
         [ 1.2054,  0.9282]]])

In [23]:
a = torch.ones((3, 7))
a

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])

In [24]:
chunker_a = torch.chunk(a, 3, dim=1)
chunker_a

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[1.],
         [1.],
         [1.]]))

In [26]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
idx = torch.tensor([0, 2])
res = torch.index_select(points, dim=0, index=idx)
res

tensor([[4., 1.],
        [2., 1.]])

In [27]:
mask = points.ge(3)
mask

tensor([[ True, False],
        [ True,  True],
        [False, False]])

In [28]:
res = torch.masked_select(points, mask)
res

tensor([4., 5., 3.])

In [7]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [8]:
points.untyped_storage()

 0
 0
 128
 64
 0
 0
 128
 63
 0
 0
 160
 64
 0
 0
 64
 64
 0
 0
 0
 64
 0
 0
 128
 63
[torch.storage.UntypedStorage(device=cpu) of size 24]

In [9]:
points_storage = points.storage()
points_storage[0]

4.0

In [10]:
points_storage[0] = 2
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [11]:
a = torch.ones(3, 2)
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [13]:
b = a.zero_()
b

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [14]:
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [15]:
points = torch.tensor([[4.0, 1.0, 3.0, 2.0], [5.0, 3.0, 7.0, 8.0], [2.0, 1.0, 9.0, 5.0], [3.0, 8.0, 4.0, 5.0]]) # 先生成一个新的tensor
second_point = points[1:,1:]
second_point

tensor([[3., 7., 8.],
        [1., 9., 5.],
        [8., 4., 5.]])

In [16]:
points.storage_offset()

0

In [17]:
second_point.storage_offset()

5

In [18]:
points.stride()

(4, 1)

In [19]:
second_point.stride()

(4, 1)

In [20]:
second_point = points[1:,1:].clone()
second_point[0,0] = 10.0
second_point

tensor([[10.,  7.,  8.],
        [ 1.,  9.,  5.],
        [ 8.,  4.,  5.]])

In [21]:
points

tensor([[4., 1., 3., 2.],
        [5., 3., 7., 8.],
        [2., 1., 9., 5.],
        [3., 8., 4., 5.]])

In [22]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [23]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [24]:
id(points.storage()) == id(points_t.storage())

True

In [25]:
points.stride()

(2, 1)

In [26]:
points_t.stride()

(1, 2)

In [28]:
points.is_contiguous()

True

In [29]:
points_t.is_contiguous()

False