In [8]:
import torch
import pandas as pd

In [9]:
points = torch.full([3, 3], 6)
points

tensor([[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]])

In [10]:
torch.save(points, 'D:/Code/PythonCode/pytorch-deep-learning-action/data/3/ourpoints.t')

In [12]:
new_p = torch.load('D:/Code/PythonCode/pytorch-deep-learning-action/data/3/ourpoints.t', weights_only=True)
new_p

tensor([[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]])

In [13]:
with open('D:/Code/PythonCode/pytorch-deep-learning-action/data/3/ourpoints.t', 'rb') as f:
    new_points = torch.load(f, weights_only=True)
new_points

tensor([[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]])

In [14]:
import h5py

In [15]:
points = torch.ones(3, 3)
f = h5py.File('D:/Code/PythonCode/pytorch-deep-learning-action/data/3/ourpoints.hdf5', 'w')
dset = f.create_dataset('points', data=points.numpy())
f.close()

In [16]:
f = h5py.File('D:/Code/PythonCode/pytorch-deep-learning-action/data/3/ourpoints.hdf5', 'r')
dset = f['points']
last_points = torch.from_numpy(dset[:])
f.close()
last_points

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [17]:
a = torch.ones((4, 5))
a

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [18]:
cat_a1 = torch.cat([a, a], dim=0)
cat_a1

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [19]:
cat_a2 = torch.cat([a, a], dim=1)
cat_a2

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [20]:
a = torch.normal(0, 1, (3, 4))
b = torch.normal(0, 1, (3, 4))
a

tensor([[-1.6491, -0.2472,  0.4581,  0.1088],
        [ 0.3564, -0.1417,  0.9881,  1.3076],
        [-0.0697, -0.2187,  1.3871,  1.2054]])

In [21]:
cat_ab1 = torch.stack([a, b], dim=0)
cat_ab1

tensor([[[-1.6491, -0.2472,  0.4581,  0.1088],
         [ 0.3564, -0.1417,  0.9881,  1.3076],
         [-0.0697, -0.2187,  1.3871,  1.2054]],

        [[-0.6229,  0.0794,  0.7143,  0.2698],
         [-0.2063, -0.2342, -0.5200,  0.9406],
         [-1.1595,  0.7688,  0.1383,  0.9282]]])

In [22]:
cat_ab2 = torch.stack([a, b], dim=2)
cat_ab2

tensor([[[-1.6491, -0.6229],
         [-0.2472,  0.0794],
         [ 0.4581,  0.7143],
         [ 0.1088,  0.2698]],

        [[ 0.3564, -0.2063],
         [-0.1417, -0.2342],
         [ 0.9881, -0.5200],
         [ 1.3076,  0.9406]],

        [[-0.0697, -1.1595],
         [-0.2187,  0.7688],
         [ 1.3871,  0.1383],
         [ 1.2054,  0.9282]]])

In [23]:
a = torch.ones((3, 7))
a

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])

In [24]:
chunker_a = torch.chunk(a, 3, dim=1)
chunker_a

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[1.],
         [1.],
         [1.]]))

In [26]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
idx = torch.tensor([0, 2])
res = torch.index_select(points, dim=0, index=idx)
res

tensor([[4., 1.],
        [2., 1.]])

In [27]:
mask = points.ge(3)
mask

tensor([[ True, False],
        [ True,  True],
        [False, False]])

In [28]:
res = torch.masked_select(points, mask)
res

tensor([4., 5., 3.])